### ISSUE TITLE
What does nagetive non-biased HSIC mean?

### ISSUE THREAD

**Issue by heng-yuwen** [phrasenmaeher/cka#1]
Hi author,

Thanks for your effort in calculating the CKA. I noticed that for some layers, the HSIC value could be negative, thus lead to nan value when calculating the CKA. Do you know what does negative HSIC mean and how to deal with it? Thanks.

**Comment by phrasenmaeher** [comment]
Thanks for reaching out to me with this! I've noticed this for myself, but the origin of the `nan`s is hard to trace. So far, I think that it stems from the calculation of the root or multiplications, where very small numbers (e.g., 0.000000123) might be used. These `nan` values don't have any meaning.

Having said this, there's now some official code by the [authors](https://arxiv.org/abs/2010.15327) available. It runs both faster than my code and produces less `nan`s. You can find it [here](https://github.com/google-research/google-research/blob/master/do_wide_and_deep_networks_learn_the_same_things/efficient_CKA.py), and I highly recommend it.
